IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'MultiShop')
BEGIN
    CREATE DATABASE MultiShop;
END;
GO

USE MultiShop;
GO

-- 1. Bảng gốc KHÔNG phụ thuộc bảng nào
CREATE TABLE TrangWeb (
    MaTrang INT IDENTITY(1,1) PRIMARY KEY,
    TenTrang NVARCHAR(50) NOT NULL,
    URL NVARCHAR(250) NOT NULL
);

CREATE TABLE PhongBan (
    MaPB VARCHAR(7) NOT NULL PRIMARY KEY,
    TenPB NVARCHAR(50) NOT NULL,
    ThongTin NVARCHAR(MAX)
);

CREATE TABLE NhanVien (
    MaNV NVARCHAR(50) NOT NULL PRIMARY KEY,
    HoTenNV NVARCHAR(50) NOT NULL,
    EmailNV NVARCHAR(50) NOT NULL,
    MatKhauNV NVARCHAR(50),
    NgaySinhNV DATE,
    GioiTinhNV BIT,
    DiaChiNV NVARCHAR(100),
    HieuLuc BIT,
    RandomKeyNV VARCHAR(50) DEFAULT CONVERT(VARCHAR(50), NEWID())
);

CREATE TABLE TrangThai (
    MaTrangThai INT NOT NULL PRIMARY KEY,
    TenTrangThai NVARCHAR(50) NOT NULL,
    DaThanhToan BIT,
    MoTa NVARCHAR(500),
    MaNV NVARCHAR(50),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE NhaCungCap (
    MaNCC NVARCHAR(50) NOT NULL PRIMARY KEY,
    TenCongTy NVARCHAR(50) NOT NULL,
    Logo NVARCHAR(50) NOT NULL,
    NguoiLienLac NVARCHAR(50),
    EmailNCC NVARCHAR(50) NOT NULL,
    DienThoaiNCC NVARCHAR(50),
    DiaChiNCC NVARCHAR(50),
    MoTaNCC NVARCHAR(MAX)
);

CREATE TABLE Loai (
    MaLoai INT IDENTITY(1,1) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL,
    TenLoaiAlias NVARCHAR(50),
    MoTa NVARCHAR(MAX),
    Hinh NVARCHAR(50)
);

-- 2. Bảng phụ thuộc
CREATE TABLE KhachHang (
    MaKH NVARCHAR(20) NOT NULL PRIMARY KEY,
    MatKhauKH NVARCHAR(50),
    HoTenKH NVARCHAR(50) NOT NULL,
    GioiTinhKH BIT NOT NULL,
    NgaySinhKH DATETIME NOT NULL,
    DiaChiKH NVARCHAR(60),
    DienThoaiKH NVARCHAR(24),
    EmailKH NVARCHAR(50) NOT NULL,
    HinhKH NVARCHAR(50),
    RandomKeyKH VARCHAR(50) DEFAULT CONVERT(VARCHAR(50), NEWID())
);

CREATE TABLE HoaDon (
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    MaKH NVARCHAR(20) NOT NULL,
    NgayDat DATETIME NOT NULL,
    NgayCan DATETIME,
    NgayGiao DATETIME,
    HoTenNguoiNhan NVARCHAR(50),
    DiaChi NVARCHAR(60) NOT NULL,
    CachThanhToan NVARCHAR(50) NOT NULL,
    CachVanChuyen NVARCHAR(50) NOT NULL,
    PhiVanChuyen FLOAT NOT NULL,
    MaTrangThai INT NOT NULL,
    MaNV NVARCHAR(50),
    GhiChu NVARCHAR(50),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    FOREIGN KEY (MaTrangThai) REFERENCES TrangThai(MaTrangThai),
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE HangHoa (
    MaHH INT IDENTITY(1,1) PRIMARY KEY,
    TenHH NVARCHAR(50) NOT NULL,
    TenAlias NVARCHAR(50),
    MaLoai INT NOT NULL,
    MoTaDonVi NVARCHAR(50),
    DonGia FLOAT,
    Hinh NVARCHAR(50),
    NgaySX DATETIME NOT NULL,
    GiamGia FLOAT NOT NULL,
    SoLanXem INT NOT NULL,
    MoTa NVARCHAR(MAX),
    MaNCC NVARCHAR(50) NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES Loai(MaLoai),
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

-- 3. Bảng liên kết
CREATE TABLE ChiTietHD (
    MaCT INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    MaHH INT NOT NULL,
    DonGia FLOAT NOT NULL,
    SoLuong INT NOT NULL,
    GiamGia FLOAT NOT NULL,
    FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    FOREIGN KEY (MaHH) REFERENCES HangHoa(MaHH)
);

CREATE TABLE YeuThich (
    MaYT INT IDENTITY(1,1) PRIMARY KEY,
    MaHH INT,
    MaKH NVARCHAR(20),
    NgayChon DATETIME,
    MoTa NVARCHAR(255),
    FOREIGN KEY (MaHH) REFERENCES HangHoa(MaHH),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE GopY (
    MaGY NVARCHAR(50) PRIMARY KEY,
    MaNV NVARCHAR(50),
    MaKH NVARCHAR(20),
    NoiDung NVARCHAR(MAX) NOT NULL,
    NgayGY DATE NOT NULL,
    HoTenKH NVARCHAR(50),
    EmailKH NVARCHAR(50),
    DienThoai NVARCHAR(50),
    CanTraLoi BIT NOT NULL,
    TraLoi NVARCHAR(50),
    NgayTL DATE,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE PhanCong (
    MaPC INT IDENTITY(1,1) PRIMARY KEY,
    MaNV NVARCHAR(50) NOT NULL,
    MaPB VARCHAR(7) NOT NULL,
    NgayPC DATETIME,
    HieuLuc BIT,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB)
);

CREATE TABLE PhanQuyen (
    MaPQ INT IDENTITY(1,1) PRIMARY KEY,
    MaPB VARCHAR(7),
    MaTrang INT,
    Them BIT NOT NULL,
    Sua BIT NOT NULL,
    Xoa BIT NOT NULL,
    Xem BIT NOT NULL,
    FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB),
    FOREIGN KEY (MaTrang) REFERENCES TrangWeb(MaTrang)
);

-- 4. View mở rộng: vChiTietHoaDon
GO
CREATE VIEW vChiTietHoaDon AS
SELECT 
    cthd.MaCT,
    cthd.MaHD,
    cthd.MaHH,
    hh.TenHH,
    cthd.DonGia,
    cthd.SoLuong,
    cthd.GiamGia,
    (cthd.DonGia * cthd.SoLuong * (1 - cthd.GiamGia / 100.0)) AS ThanhTien
FROM ChiTietHD cthd
JOIN HangHoa hh ON hh.MaHH = cthd.MaHH;
GO
